---

# Hostname, DNS, pts
- name: Post-Install | | Allow login from pts/0
  copy: src=securetty dest={{ sles_containers_root }}/{{ container.name }}/etc/securetty

- name: Post-Install | | Set hostname
  shell: "echo {{ container.name }} > {{ sles_containers_root }}/{{ container.name }}/etc/hostname"

- name: Post-Install | | Set the DNS servers
  shell: cp /etc/resolv.conf {{ sles_containers_root }}/{{ container.name }}/etc/resolv.conf

#- name: Post-Install | | Create an empty default config file for network
#  file: path={{ sles_containers_root }}/{{ container.name }}/etc/sysconfig/network state=touch

# Custom files

- name: Post-Install | | Create custom directories
  file: path={{ sles_containers_root }}/{{ container.name }}/{{ item }} state=directory owner=root
  with_items:
    - /etc/ansible/facts.d
    - /etc/pacemaker

- name: Post-Install | | Pacemaker authkey
  copy: src=/etc/pacemaker/authkey dest={{ sles_containers_root }}/{{ container.name }}/etc/pacemaker/authkey remote_src=true
  when: pacemaker_authkey.stat.exists == true

# Networking

- name: Post-Install | | Create interfaces configurations
  template: src=ifcfg-interface.j2 dest={{ sles_containers_root }}/{{ container.name }}/etc/sysconfig/network/ifcfg-{{ item.interface }}
  with_items: "{{container.ips}}"

- name: Post-Install | | Set routes
  template: src=ifroute-interface.j2 dest={{ sles_containers_root }}/{{ container.name }}/etc/sysconfig/network/ifroute-{{ item.interface }}
  with_items: "{{container.ips}}"
  when: item.gateway is defined and item.gateway != 'None'

# Services

- name: Post-Install | | Start sshd at boot time
  file: src=/usr/lib/systemd/system/{{ item }} dest={{ sles_containers_root }}/{{ container.name }}/etc/systemd/system/multi-user.target.wants/{{ item }} state=link
  with_items:
    - sshd.service
